### ISSUE TITLE
summary.get_diff generates a "TypeError: 'type' object is not subscriptable"

### ISSUE THREAD

**Issue by azmeuk** [pympler/pympler#126]
With python 3.9 and pympler 0.9:

```python
from pympler import muppy, summary
before = muppy.get_objects()
print()
after = muppy.get_objects()
diff = summary.get_diff(before, after)
summary.print_(diff)
```
generates this error stack:
```python
Traceback (most recent call last):
  File ".../test.py", line 5, in <module>
    diff = summary.get_diff(before, after)
  File ".../env/lib/python3.9/site-packages/pympler/summary.py", line 147, in get_diff
    right_by_key = dict((r[0], r) for r in right)
  File ".../env/lib/python3.9/site-packages/pympler/summary.py", line 147, in <genexpr>
    right_by_key = dict((r[0], r) for r in right)
TypeError: 'type' object is not subscriptable
```

**Comment by azmeuk** [comment]
Nevermind, I got this line wrong:
```python
diff = summary.get_diff(summary.summarize(before), summary.summarize(after))
```
