### ISSUE TITLE
cannot create weak reference to '_EmptyListener' object

### ISSUE THREAD

**Issue by SteffRainville** [pympler/pympler#146]
Windows 11
Python 3.10.4 64 bits

Trying to measure the size of a SQLAlchemy create_engine instance

engine1 = create_engine(sqlite_url, echo=True)
s = asizeof.asizeof(engine1)

Exception has occurred: TypeError
cannot create weak reference to '_EmptyListener' object

**Comment by mrJean1** [comment]
Could you please send the entire stack traceback of that error?  It is not possible to debug the issue without that.

**Comment by SteffRainville** [comment]
Is that sufficient ?

Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\main.py", line 29, in <module>
    s = asizeof.asizeof(engine1)
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 2603, in asizeof
    s = _asizer.asizeof(*t)
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 2032, in asizeof
    return sum(self._sizer(o, 0, 0, None) for o in objs)
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 2032, in <genexpr>
    return sum(self._sizer(o, 0, 0, None) for o in objs)
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 1964, in _sizer
    s += z(o, i, d, None)
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 1964, in _sizer
    s += z(o, i, d, None)
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 1964, in _sizer
    s += z(o, i, d, None)
  [Previous line repeated 2 more times]
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 1963, in _sizer
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\pympler\asizeof.py", line 396, in _dir2
    if hasattr(obj, a):
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1220, in __getattr__
    value = getattr(self, "_memoized_attr_%s" % key)()
  File "c:\DEV\SOURCE\PERSO\pyrefast\server\venv\lib\site-packages\sqlalchemy\event\attr.py", line 51, in _memoized_attr_ref
    return weakref.ref(self, registry._collection_gced)
TypeError: cannot create weak reference to '_EmptyListener' object

**Comment by mrJean1** [comment]
Yes, that helps.  Thank you.  Which version of `pympler.asizeof` is this?  Type this line
```
    python[3]  -m  pympler.asizeof  -v
```
in a command window.

**Comment by mrJean1** [comment]
It is unclear why the `hasattr` call on line 396 (of `asizeof.py` version `21.08.09`) causes a `TypeError`
```
                for a in getattr(c, slots, ()):
                    if a.startswith('__'):
                        a = '_' + c.__name__ + a
                    if hasattr(obj, a):
                        s.setdefault(a, getattr(obj, a))
```
Simply adding some lines around that will avoid the exception, for example
```
                for a in getattr(c, slots, ()):
                    if a.startswith('__'):
                        a = '_' + c.__name__ + a
                    try:
                        if hasattr(obj, a):
                            s.setdefault(a, getattr(obj, a))
                    except TypeError:
                        pass
```
and that will be a forthcoming patch for `asizeof.py`.  There is not much else which can be done, unfortunately.

**Comment by SteffRainville** [comment]
> python[3]  -m  pympler.asizeof  -v

venv\lib\site-packages\pympler\asizeof.py 21.08.09 (Python 3.10.4 64bit)

**Comment by SteffRainville** [comment]
The try catch worked and I got the engine memory footprint. Thanks

**Comment by mrJean1** [comment]
Great!  There may be a few bytes missing in the total reported, hope that is acceptable.

The problem occurs in a `sqlalchemy` class handling `"memoized slots"`, but the cause of the `weakref` problem is unclear.  In Python 2 `__slots__` used to be a worthwhile feature (`asizeof.py` uses `__slots__` for certain classes.  But Python 3 has improved the storage and performance of `dict` and `__dict__`,  making `__slots__` less useful.

Please close the issue if no longer needed.
