### ISSUE TITLE
test failures with python 3.11

### ISSUE THREAD

**Issue by rathann** [pympler/pympler#148]
When running the Pympler-1.0.1 testsuite under python 3.11 on Fedora rawhide (development branch), the following failures can be observed:
```
$ PYTHONPATH=/builddir/build/BUILDROOT/python-Pympler-1.0.1-3.fc37.noarch/usr/lib/python3.11/site-packages /usr/bin/python3 setup.py test
running test
test_otracker_diff (muppy.test_tracker.TrackerTest.test_otracker_diff)
Test object tracker diff. ... ok
...
Test process sizes match: ps util vs getrusage ... ok
test_ps_vs_proc_sizes (test_process.ProcessMemoryTests.test_ps_vs_proc_sizes)
Test process sizes match: ps util vs /proc/self/stat ... ok
======================================================================
ERROR: test_all (asizeof.test_asizeof.AsizeofDemos.test_all)
Test all=True example
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Pympler-1.0.1/test/asizeof/test_asizeof.py", line 522, in test_all
    asizeof.asizeof(limit=self.MAX, code=True, stats=self.MAX, all=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILDROOT/python-Pympler-1.0.1-3.fc37.noarch/usr/lib/python3.11/site-packages/pympler/asizeof.py", line 2603, in asizeof
    _asizer.print_stats(objs=t, opts=opts)  # show opts as _kwdstr
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILDROOT/python-Pympler-1.0.1-3.fc37.noarch/usr/lib/python3.11/site-packages/pympler/asizeof.py", line 2251, in print_stats
    self.print_profiles(w=w, cutoff=c, **print3options)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILDROOT/python-Pympler-1.0.1-3.fc37.noarch/usr/lib/python3.11/site-packages/pympler/asizeof.py", line 2191, in print_profiles
    for v, k in sorted(t, reverse=True):
                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'type' and 'type'
======================================================================
FAIL: test_findgarbage (gui.test_garbage.GarbageTestCase.test_findgarbage)
Test garbage annotation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Pympler-1.0.1/test/gui/test_garbage.py", line 87, in test_findgarbage
    self.assertTrue(gbar.size > 0, gbar.size)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: False is not true : 0
======================================================================
FAIL: test_prune (gui.test_garbage.GarbageTestCase.test_prune)
Test pruning of reference graph.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Pympler-1.0.1/test/gui/test_garbage.py", line 153, in test_prune
    self.assertEqual(gb2.num_in_cycles, 2)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 0 != 2
======================================================================
FAIL: test_get_tree (muppy.test_refbrowser.TreeTest.test_get_tree)
Test reference browser tree representation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Pympler-1.0.1/test/muppy/test_refbrowser.py", line 155, in test_get_tree
    self.assertTrue(r in children)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: False is not true
----------------------------------------------------------------------
Ran 126 tests in 49.562s
FAILED (failures=3, errors=1)
gc:0: ResourceWarning: gc: 139 uncollectable objects at shutdown; use gc.set_debug(gc.DEBUG_UNCOLLECTABLE) to list them
```

**Comment by mrJean1** [comment]
Version 22.06.30 of module `asizeof.py` sumitted as pull request 149 contains a fix for the `TypeError: '<' not supported …`.

**Comment by rathann** [comment]
> Version 22.06.30 of module `asizeof.py` sumitted as pull request #149 contains a fix for the `TypeError: '<' not supported …`.

I can confirm the TypeError exception is fixed by the patch.

**Comment by mcepl** [comment]
Also, `inspect.getargspec` was truly removed in 3.11.0:
```diff
---
 pympler/util/bottle.py |    6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

--- a/pympler/util/bottle.py
+++ b/pympler/util/bottle.py
@@ -41,7 +41,7 @@ import base64, cgi, email.utils, functoo
 from datetime import date as datedate, datetime, timedelta
 from tempfile import TemporaryFile
 from traceback import format_exc, print_exc
-from inspect import getargspec
+from inspect import getfullargspec
 from unicodedata import normalize
 
 
@@ -554,7 +554,7 @@ class Route(object):
         ''' Return a list of argument names the callback (most likely) accepts
             as keyword arguments. If the callback is a decorated function, try
             to recover the original function before inspection. '''
-        return getargspec(self.get_undecorated_callback())[0]
+        return getfullargspec(self.get_undecorated_callback())[0]
 
     def get_config(self, key, default=None):
         ''' Lookup a config field and return its value, first checking the
@@ -2645,7 +2645,7 @@ def yieldroutes(func):
         d(x=5, y=6) -> '/d' and '/d/<x>' and '/d/<x>/<y>'
     """
     path = '/' + func.__name__.replace('__','/').lstrip('/')
-    spec = getargspec(func)
+    spec = getfullargspec(func)
     argc = len(spec[0]) - len(spec[3] or [])
     path += ('/<%s>' * argc) % tuple(spec[0][:argc])
     yield path
```

**Comment by rathann** [comment]
> Also, `inspect.getargspec` was truly removed in 3.11.0:
> 
> ```diff
> ---
>  pympler/util/bottle.py |    6 +++---

This is an old version of bottle bundled with Pympler. The Fedora package unbundles this, so it's not affected.

**Comment by Trophime** [comment]
Running latest release testsuite on Debian Bookworm with python 3.11.1, I also run into some errors:
```
======================================================================
FAIL: test_get_tree (muppy.test_refbrowser.TreeTest.test_get_tree)
Test reference browser tree representation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pympler-1.0.1+dfsg1/test/muppy/test_refbrowser.py", line 155, in test_get_tree
    self.assertTrue(r in children)
AssertionError: False is not true

======================================================================
FAIL: test_findgarbage (gui.test_garbage.GarbageTestCase.test_findgarbage)
Test garbage annotation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pympler-1.0.1+dfsg1/test/gui/test_garbage.py", line 87, in test_findgarbage
    self.assertTrue(gbar.size > 0, gbar.size)
AssertionError: False is not true : 0

======================================================================
FAIL: test_prune (gui.test_garbage.GarbageTestCase.test_prune)
Test pruning of reference graph.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pympler-1.0.1+dfsg1/test/gui/test_garbage.py", line 153, in test_prune
    self.assertEqual(gb2.num_in_cycles, 2)
AssertionError: 0 != 2

----------------------------------------------------------------------
Ran 126 tests in 28.963s

FAILED (failures=3)
```

NB: I applied the patch from @mcepl
