### ISSUE TITLE
asizeof(obj) leads to a negative base ValueError

### ISSUE THREAD

**Issue by avivajpeyi** [pympler/pympler#151]
I am trying to estimate the size of a python object that is a subclass of an [`astropy.Table`](https://docs.astropy.org/en/latest/api/astropy.table.Table.html#astropy.table.Table)

However, I receive a `ValueError: invalid option: base=-391848` error. 

Does anyone have suggestions on why this is occurring/how I can fix this? 

### MWE: 
```python
%pip install -q lightkurve
%pip install -q pympler

import lightkurve as lk
from pympler import asizeof
import numpy as np
import os

lc = lk.search_lightcurve("TOI 588", author="SPOC").download_all().stitch().remove_nans()
asizeof.asizeof(lc)
```

```log
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-13-88b6425eddfd>](https://localhost:8080/#) in <module>()
      8 
      9 lc = lk.search_lightcurve("TOI 588", author="SPOC").download_all().stitch().remove_nans()
---> 10 asizeof.asizeof(lc)

30 frames
[/usr/local/lib/python3.7/dist-packages/pympler/asizeof.py](https://localhost:8080/#) in reset(self, base, item, leng, refs, both, kind, type, vari)
   1190         '''
   1191         if base < 0:
-> 1192             raise ValueError('invalid option: %s=%r' % ('base', base))
   1193         else:
   1194             self.base = base

ValueError: invalid option: base=-391848
```

**Comment by mrJean1** [comment]
What is the version of `pympler` and `asizeof`?

**Comment by avivajpeyi** [comment]
pympler.__version__: 1.0.1
asizeof.__version__: 21.08.09


`type(lc)` is [`lightkurve.lightcurve.TessLightCurve`](https://docs.lightkurve.org/reference/lightcurve.html)

However, this is the `LightCurve` class inherits from [astropy.Table]. (https://docs.astropy.org/en/latest/api/astropy.table.Table.html#astropy.table.Table)

> [Table](https://docs.astropy.org/en/latest/api/astropy.table.Table.html#astropy.table.Table) provides a class for heterogeneous tabular data. A key enhancement provided by the [Table](https://docs.astropy.org/en/latest/api/astropy.table.Table.html#astropy.table.Table) class over e.g. a [numpy](https://numpy.org/doc/stable/reference/index.html#module-numpy) structured array is the ability to easily modify the structure of the table by adding or removing columns, or adding new rows of data. In addition table and column metadata are fully supported.

At the moment I have switched to use `bytes = len(pickle.dumps(obj))` in place of `bytes = asizeof(obj)`

**Comment by mrJean1** [comment]
CORRECTION.  Thank you!  I'm able to duplicate the problem with Python 3.10.5 (on macOS and Apple Si), but _only with_ `asizeof` version _21.08.09 or older_.  More recent versions `do not exhibit` the issue, however those may not have been pulled into `pympler` yet.

Here is [a link](https://www.dropbox.com/s/t7ud8l24x7o4iap/asizeof220630.py?dl=0) to `asizeof` version _22.06.30_ for your consideration.  Instead of ...
```
from pympler import asizeof
...
```
use ...
```
import asizeof220630 as asizeof
...
```

**Comment by mrJean1** [comment]
In case you need to use other parts of `pympler`, just replace the module `…/site-packages/pympler/asiszeof.py` with `asizeof220630.py` renamed to `asizeof.py`.

**Comment by whateverforever** [comment]
Got the same issue with the latest version from pypi

```
Python 3.8.10
numpy==1.22.1
Pympler==1.0.1
trimesh==3.23.5
```

```
In [1]: import trimesh

In [2]: a = trimesh.load(".../model.ply", validate=False, process=False)

In [3]: from pympler import asizeof

In [5]: asizeof.asizeof(a)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 asizeof.asizeof(a)

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:2603, in asizeof(*objs, **opts)
   2601 if x:  # don't size, profile or rank _getobjects tuple
   2602     _asizer.exclude_objs(t)
-> 2603 s = _asizer.asizeof(*t)
   2604 _asizer.print_stats(objs=t, opts=opts)  # show opts as _kwdstr
   2605 _asizer._clear()

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:2032, in Asizer.asizeof(self, *objs, **opts)
   2030     self.set(**opts)
   2031 self.exclude_refs(*objs)  # skip refs to objs
-> 2032 return sum(self._sizer(o, 0, 0, None) for o in objs)

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:2032, in <genexpr>(.0)
   2030     self.set(**opts)
   2031 self.exclude_refs(*objs)  # skip refs to objs
-> 2032 return sum(self._sizer(o, 0, 0, None) for o in objs)

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:1964, in Asizer._sizer(self, obj, pid, deep, sized)
   1962 else:  # just size and accumulate
   1963     for o in v.refs(obj, False):
-> 1964         s += z(o, i, d, None)
   1965 # deepest recursion reached
   1966 if self._depth < d:

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:1964, in Asizer._sizer(self, obj, pid, deep, sized)
   1962 else:  # just size and accumulate
   1963     for o in v.refs(obj, False):
-> 1964         s += z(o, i, d, None)
   1965 # deepest recursion reached
   1966 if self._depth < d:

    [... skipping similar frames: Asizer._sizer at line 1964 (2 times)]

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:1964, in Asizer._sizer(self, obj, pid, deep, sized)
   1962 else:  # just size and accumulate
   1963     for o in v.refs(obj, False):
-> 1964         s += z(o, i, d, None)
   1965 # deepest recursion reached
   1966 if self._depth < d:

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:1937, in Asizer._sizer(self, obj, pid, deep, sized)
   1935 v = _typedefs.get(k, None)
   1936 if not v:  # new typedef
-> 1937     _typedefs[k] = v = _typedef(obj, derive=self._derive_,
   1938                                      frames=self._frames_,
   1939                                       infer=self._infer_)
   1940 if (v.both or self._code_) and v.kind is not self._ign_d:
   1941     s = f = v.flat(obj, self._mask)  # flat size

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:1597, in _typedef(obj, derive, frames, infer)
   1595     v.set(refs=_namedtuple_refs)
   1596 elif numpy and _isnumpy(obj):  # NumPy data
-> 1597     v.set(**_numpy_kwds(obj))
   1598     if _numpy_excl:
   1599         _getsizeof_excls_add(t)

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:1183, in _Typedef.set(self, safe_len, **kwds)
   1181     d = self.kwds()
   1182     d.update(kwds)
-> 1183     self.reset(**d)
   1184 if safe_len and self.item:
   1185     self.leng = _len

File ~/.local/lib/python3.8/site-packages/pympler/asizeof.py:1192, in _Typedef.reset(self, base, item, leng, refs, both, kind, type, vari)
   1189 '''Reset all specified attributes.
   1190 '''
   1191 if base < 0:
-> 1192     raise ValueError('invalid option: %s=%r' % ('base', base))
   1193 else:
   1194     self.base = base

ValueError: invalid option: base=-2599240
```

**Comment by mrJean1** [comment]
Is there a small script which reproduces the problem?

**Comment by flying-sheep** [comment]
PR #145 was closed as superseded by the merged #149, but I still see

```pytb
Traceback (most recent call last):
  File "…/site-packages/asv_runner/benchmarks/mem.py", line 75, in run
    sizeof2 = asizeof([obj, obj])
              ^^^^^^^^^^^^^^^^^^^
  File "…/site-packages/pympler/asizeof.py", line 2545, in asizeof
    s = _asizer.asizeof(*t)
        ^^^^^^^^^^^^^^^^^^^
  File "…/site-packages/pympler/asizeof.py", line 1954, in asizeof
    return sum(self._sizer(o, 0, 0, None) for o in objs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/site-packages/pympler/asizeof.py", line 1954, in <genexpr>
    return sum(self._sizer(o, 0, 0, None) for o in objs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/site-packages/pympler/asizeof.py", line 1888, in _sizer
    s += z(o, i, d, None)
         ^^^^^^^^^^^^^^^^
  File "…/site-packages/pympler/asizeof.py", line 1888, in _sizer
    s += z(o, i, d, None)
         ^^^^^^^^^^^^^^^^
  File "…/site-packages/pympler/asizeof.py", line 1888, in _sizer
    s += z(o, i, d, None)
         ^^^^^^^^^^^^^^^^
  [Previous line repeated 10 more times]
  File "…/site-packages/pympler/asizeof.py", line 1861, in _sizer
    _typedefs[k] = v = _typedef(obj, derive=self._derive_,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/site-packages/pympler/asizeof.py", line 1530, in _typedef
    v.set(**_numpy_kwds(obj))
  File "…/site-packages/pympler/asizeof.py", line 1142, in set
    self.reset(**d)
  File "…/site-packages/pympler/asizeof.py", line 1114, in reset
    raise _OptionError(self.reset, **e)
ValueError: invalid option: reset(base=-261792)
asv: benchmark failed (exit status 1)
```

**Comment by mrJean1** [comment]
Will investigate.

**Comment by mrJean1** [comment]
The issue is _not_ reproducable with `asizeof` versions 22.06.30, 22.12.07 nor 23.11.15 using `python` 3.10.8, `lightkurve` 2.4.2 and `numpy` 1.23.3 (on macOS).  `Pympler` 1.1 includes `asizeof` 22.12.07.

```
import lightkurve as lk
# import pympler
import asizeofYYMMDD as asizeof
import numpy as np
import os

# print(f"pympler.__version__: {pympler.__version__}")
print(f"lightkurve.__version__: {lk.__version__}")
print(f"asizeof.__version__: {asizeof.__version__}")
print(f"numpy.__version__: {np.__version__}")

lc = lk.search_lightcurve("TOI 588", author="SPOC").download_all().stitch().remove_nans()
asizeof.asizeof(lc)


% python3.10 pymp151.py
lightkurve.__version__: 2.4.2
asizeof.__version__: 22.06.30
numpy.__version__: 1.23.3

% python3.10 pymp151.py
lightkurve.__version__: 2.4.2
asizeof.__version__: 22.12.07
numpy.__version__: 1.23.3

% python3.10 pymp151.py
lightkurve.__version__: 2.4.2
asizeof.__version__: 23.11.15
numpy.__version__: 1.23.3

```

**Comment by TheFantasticWarrior** [comment]
`print(asizeof.asizeof(np.tile(None,(10,10))))` seems to cause the same error, however
```
print(asizeof.asizeof(np.tile(None,(10,10)).astype(object)))
print(asizeof.asizeof(np.tile(None,(10,10))))
```
this doesn't
both are the same type
```
<class 'numpy.dtypes.ObjectDType'>
<class 'numpy.dtypes.ObjectDType'>
```
asizeof.__version__: 22.12.07
numpy.__version__: 2.0.1

**Comment by wannadream** [comment]
Tested with the latest version. The error seems gone.

**Comment by mrJean1** [comment]
Thank you!

**Comment by r-xue** [comment]
Hi there, is the latest version of `asizeof.py` planned for the next `Pympler` release? Thank you! Specifically, any anticipated timeline for #164 to merge?

**Comment by jhlegarreta** [comment]
I was encountering this issue in a project that I contribute to, but the 24.08.21 version seems not to solve the issue. The lines at issue are pointed below: 

https://github.com/jhlegarreta/nifreeze/blob/1354129f12f5018af27c05a976ab45bc41ce9f43/benchmarks/benchmarks/bench_data.py#L127-L133

https://github.com/jhlegarreta/nifreeze/blob/1354129f12f5018af27c05a976ab45bc41ce9f43/benchmarks/benchmarks/bench_data.py#L164-L170

The data contained/returned by the class instance at issue is numpy arrays.

**Comment by mrJean1** [comment]
Please show …

1) which version of `pympler` and `asizeof` you are using and …

2) a stack trace of several levels but only if there is an exception raised.

**Comment by jhlegarreta** [comment]
- `Pympler` 1.1
- `asizeof` 22.12.07
- Commented the `skip_benchmark_if(True)` statement for the `DWIBenchmark.mem_getitem` function in the linked benchmarking file, ran `asv run --show-stderr` and the following is displayed:

```

[52.17%] ··· bench_data.DWIBenchmark.mem_getitem failed
[52.17%] ···· Traceback (most recent call last):
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/asv_runner/server.py",
 line 179, in _run_server
                  _run(run_args)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/asv_runner/run.py",
 line 72, in _run
                  result = benchmark.do_run()
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/asv_runner/benchmarks/_base.py",
 line 661, in do_run
                  return self.run(*self._current_params)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/asv_runner/benchmarks/mem.py",
 line 75, in run
                  sizeof2 = asizeof([obj, obj])
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 2545, in asizeof
                  s = _asizer.asizeof(*t)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1954, in asizeof
                  return sum(self._sizer(o, 0, 0, None) for o in objs)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1954, in <genexpr>
                  return sum(self._sizer(o, 0, 0, None) for o in objs)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1888, in _sizer
                  s += z(o, i, d, None)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1888, in _sizer
                  s += z(o, i, d, None)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1861, in _sizer
                  _typedefs[k] = v = _typedef(obj, derive=self._derive_,
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1530, in _typedef
                  v.set(**_numpy_kwds(obj))
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1142, in set
                  self.reset(**d)
File "/home/src/nifreeze/benchmarks/env/b381fad5/lib/python3.10/site-packages/pympler/asizeof.py",
 line 1114, in reset
                  raise _OptionError(self.reset, **e)
ValueError: invalid option: reset(base=-16240)
asv: benchmark failed (exit status 1)
```

**Comment by mrJean1** [comment]
`Pympler 1.1` is the latest available but it does not include several updates to `asizeof`, 22.12.07 is too old.

Rename the `asizeof.py` file in your `pympler` module.  Then, download this [asizeof.py](https://www.dropbox.com/scl/fi/gn34dh1acbnzdbcfwr1k5/asizeof250728.py?rlkey=c1msng4vh06d33v85d99fnz0h&dl=0) and put that into the same `pympler` module/folder/directory as the renamed one.

HTH, but may not.  And sorry about the hassle.

**Comment by jhlegarreta** [comment]
Unfortunately, I get the same result that I got with the previous version, including the line numbers/statements reported by the stack trace.

**Comment by mrJean1** [comment]
For got to mention, make sure to rename the downloaded file `asizeof250728.py` to `asizeof.py` before installation.

Line 1114 of `asizeof.py 22.12.07` is the `raise _OptionError(...)` shown in the stack traceback.  With `asizeof.py 25.07.28` installed as mentioned above, the stack traceback should show line 1348.  To check the `asizeof` version, type ...
```
python3 -m pympler.asizeof
```
or
```
python3
from pympler import asizeof
print(asizeof.__version__)
```

**Comment by jhlegarreta** [comment]
👍 My bad; the issue was that I was replacing the file in the general virtual environment, but `asv` creates its own virtual environment, which is the one used to run the benchmark. Substituting the file at issue in the `asv` environment allows all functions to run. I see that the `mem_getitem` benchmarks return a value of 0, but the rest of the benchmarks at issue return a reasonable value, so now it may be more an issue unrelated to `pympler`. I confess that all line numbers being the same was suspicious and I should have investigated more, so my apologies.

Is a release containing these bug fixes planned?

**Comment by mrJean1** [comment]
Yes, new releases are forthcoming, just not sure when yet ;(

Where does `asv` pull `pympler` from?  Would pre-installing `pympler` into `python` help?

**Comment by jhlegarreta** [comment]
`asv` will pull dependencies from the `matrix` property in https://asv.readthedocs.io/en/latest/using.html#setting-up-a-new-benchmarking-project. `pympler` is a dependency of `asv` itself.

**Comment by mrJean1** [comment]
[Here](https://www.dropbox.com/scl/fi/ltb6m2na5zh1f7pqdso5p/pympler-1.1.1.tar.gz?rlkey=u6jvmr04b9fti8gu01dchc7mh&dl=0) is a copy of `pympler 1.1 `with `asizeof.py` version 25.07.28, packaged as [pympler-1.1.1.tar.gz](https://www.dropbox.com/scl/fi/ltb6m2na5zh1f7pqdso5p/pympler-1.1.1.tar.gz?rlkey=u6jvmr04b9fti8gu01dchc7mh&dl=0).  

Perhaps, you can direct `asv matrix` to load `pympler` from that package instead of the original `pympler-1.1` from PyPI.

Or change the Python code inside your project where `pympler` is imported to something like `import pympler111 as pympler`.

**Comment by jhlegarreta** [comment]
Thanks for the effort @mrJean1; we run benchmarking through GHA, so we will wait until a new version is released. `asv` will use the latest `pympler` version as soon as it is available as they do not pin it: https://github.com/airspeed-velocity/asv/blob/main/pyproject.toml#L49. We do not pin `asv` either, so when that happens the relevant benchmarking functions should pass.
