### ISSUE TITLE
failures=2 in testsuite of pympler-0.3.1 under python3.4

### ISSUE THREAD

**Issue by idella** [pympler/pympler#19]
with deps installed

```bash
/path/to//Pympler-0.3.1/ $ python3.4 setup.py try

======================================================================
FAIL: test_uncollectable (gui.test_garbage.GarbageTestCase)
Test uncollectable object tracking.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/test/gui/test_garbage.py", line 226, in test_uncollectable
    self.assertEqual(len(genemy), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_flatsize_vs_getsizeof (asizeof.test_asizeof.AsizeofTest)
Test asizeof.flatsize() vs sys.getsizeof()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/test/asizeof/test_asizeof.py", line 26, in test_flatsize_vs_getsizeof
    n, e = f(failf=self._failf)  # stdf=sys.stderr)
  File "/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/pympler/asizeof.py", line 2276, in test_flatsize
    a, s, _nameof(type(o)), _repr(o))
  File "/mnt/gen2/TmpDir/portage/dev-python/pympler-0.3.1/work/Pympler-0.3.1/test/asizeof/test_asizeof.py", line 17, in _failf
    self.fail(fmt % args)
AssertionError: 104 vs 616 for deque: deque([])

----------------------------------------------------------------------
Ran 114 tests in 17.571s

FAILED (failures=2)
```

also acquired the same output by use of python3.4 -m unittest discover.  They pass under py3.3

Can you replicate?  Do you require any further info?

**Comment by Pankrat** [comment]
Hi, Python 3.4 support was only added in Pympler 0.4.0 (https://github.com/pympler/pympler/blob/master/CHANGELOG#L24). Could you use Pympler 0.4 instead of 0.3.1?
