### ISSUE TITLE
latest release: 2 tests fails

### ISSUE THREAD

**Issue by Trophime** [pympler/pympler#47]
Just to let you know that 2 tests fail beside the problem with gui test for latest release when building as a package in Debian/testing

```
test.muppy.test_tracker (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test_flatsize_vs_getsizeof (test.asizeof.test_asizeof.AsizeofTest)
Test asizeof.flatsize() vs sys.getsizeof()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/asizeof/test_asizeof.py", line 82, in test_flatsize_vs_getsizeof
    n, e = test_flatsize(failf=self._failf)  # stdf=sys.stderr)
  File "test/asizeof/test_asizeof.py", line 31, in test_flatsize
    t.append(v.type())
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 234, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: True

======================================================================
ERROR: test.muppy.test_tracker (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.muppy.test_tracker
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "test/muppy/test_tracker.py", line 8, in <module>
    from testutils import disable
ImportError: No module named testutils


----------------------------------------------------------------------
Ran 101 tests in 170.602s
```

**Comment by Pankrat** [comment]
Sorry, looks like I've missed your reports in my notifications.

I've re-enabled the tracker test on the master branch which should fix the import error. The other test has already been removed as it has been failing all the time for no good reason and it was only relevant for Python 2.5 support anyway. Please let me know if you still experience test failures. Pympler 0.5 should be released during the next few days.
