### ISSUE TITLE
test fails during conda-build

### ISSUE THREAD

**Issue by CJ-Wright** [pympler/pympler#48]
I keep getting the following error during the conda build
```python
FAIL: test_flatsize_vs_getsizeof (asizeof.test_asizeof.AsizeofTest)
Test asizeof.flatsize() vs sys.getsizeof()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/staged-recipes/build_artefacts/pympler_1488917080907/test_tmp/test/asizeof/test_asizeof.py", line 82, in test_flatsize_vs_getsizeof
    n, e = test_flatsize(failf=self._failf)  # stdf=sys.stderr)
  File "/staged-recipes/build_artefacts/pympler_1488917080907/test_tmp/test/asizeof/test_asizeof.py", line 63, in test_flatsize
    a, s, asizeof._nameof(type(o)), _repr(o))
  File "/staged-recipes/build_artefacts/pympler_1488917080907/test_tmp/test/asizeof/test_asizeof.py", line 76, in _failf
    self.fail(fmt % args)
AssertionError: 904 vs 984 for type: <class 'asizeof.test_asizeof.T'>
```
Can someone tell me what is going wrong?

**Comment by CJ-Wright** [comment]
please see https://github.com/conda-forge/staged-recipes/pull/2558

**Comment by Pankrat** [comment]
This test has been removed together with Python 2.5 support. Could you test again?

**Comment by CJ-Wright** [comment]
Sure, do you want to be on the maintainers list? (sorry if I asked this already)

**Comment by CJ-Wright** [comment]
It works!
