### ISSUE TITLE
pyasn1.error.PyAsn1Error: Uninitialized ASN.1 value ("__sizeof__" attribute looked up)

### ISSUE THREAD

**Issue by fvisin** [pympler/pympler#51]
The following error occurs when I create a `SummaryTracker` in my code, is there any way I can prevent this from happening? Thanks!

``` python
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from main_loop_tf.main import run
  File "/home/francesco/exp/main_loop_tf/main_loop_tf/main.py", line 39, in <module>
    tr = tracker.SummaryTracker()
  File "/home/francesco/.local/lib/python2.7/site-packages/pympler/tracker.py", line 45, in __init__
    self.s0 = summary.summarize(muppy.get_objects())
  File "/home/francesco/.local/lib/python2.7/site-packages/pympler/summary.py", line 126, in summarize
    total_size[otype] = getsizeof(o)
  File "/home/francesco/.local/lib/python2.7/site-packages/pyasn1/type/base.py", line 145, in plug
    raise error.PyAsn1Error('Uninitialized ASN.1 value ("%s" attribute looked up)' % name)
pyasn1.error.PyAsn1Error: Uninitialized ASN.1 value ("__sizeof__" attribute looked up)
```

**Comment by Pankrat** [comment]
Which Python version are you using?

Looks like one of the types in pyasn1 (if that's what you're using) doesn't support [sys.getsizeof](https://docs.python.org/3/library/sys.html#sys.getsizeof).

**Comment by fvisin** [comment]
I am using Python 2.7.12 on Ubuntu 16.04:
```bash
uname -a
Linux fraptop 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

And this is the version of pyasn1:
```python
In [1]: import pyasn1
In [2]: pyasn1.__version__
Out[2]: '0.2.2'
```

**Comment by JohnGarbutt** [comment]
FWIW, I hit the same issue with pyan1. While that lib needs fixing, I went for a very nasty hack:

```
def summarize(objects):
    """Summarize an objects list.

    Return a list of lists, whereas each row consists of::
      [str(type), number of objects of this type, total size of these objects].

    No guarantee regarding the order is given.

    """
    count = {}
    total_size = {}
    for o in objects:
        otype = _repr(o)
        try:
            size = getsizeof(o)
        except:
            print "Warning failed getsizeof: %s" % otype
            size = 0
        if otype in count:
            count[otype] += 1
            total_size[otype] += size
        else:
            count[otype] = 1
            total_size[otype] = size
    rows = []
    for otype in count:
        rows.append([otype, count[otype], total_size[otype]])
    return rows
```

**Comment by fvisin** [comment]
Thanks for sharing!
