### ISSUE TITLE
KeyError: <class 'django.template.base.Template'>

### ISSUE THREAD

**Issue by markddavidoff** [pympler/pympler#55]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/views/debug.py", line 84, in technical_500_response
    html = reporter.get_traceback_html()
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/views/debug.py", line 326, in get_traceback_html
    t = DEBUG_ENGINE.from_string(TECHNICAL_500_TEMPLATE)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/django/template/engine.py", line 155, in from_string
    return Template(template_code, engine=self)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py", line 335, in <lambda>
    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py", line 310, in _tracker
    _observer_.init(_self_, *args, **kwds)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py", line 335, in <lambda>
    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py", line 310, in _tracker
    _observer_.init(_self_, *args, **kwds)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py", line 335, in <lambda>
    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py", line 310, in _tracker
    _observer_.init(_self_, *args, **kwds)
  File "/Users/markddavidoff/Dev/Envs/webenv/lib/python2.7/site-packages/pympler/classtracker.py", line 335, in <lambda>
    lambda *args, **kwds: func(self._observers[cls], *args, **kwds),
KeyError: <class 'django.template.base.Template'>

**Comment by markddavidoff** [comment]
Django 1.11.3

**Comment by karolyi** [comment]
+1

I'm getting something similar, and it seems Django is the cause:

```python
.../venv/lib/python3.6/site-packages/pympler/asizeof.py in save(self, t, base, heap):
KeyError: "asizeof typedef (48, 0, None, None, True, 'static', <class 'range'>) bad: (<class 'range' def>, <class 'range'>) True"
```

**Comment by mrJean1** [comment]
I’m investigating this.

/Jean

**Comment by Schnouki** [comment]
Commit https://github.com/beijaflor-io/pympler/commit/b4bbbbacc9ba53d112b42e841b7312e21d51796c fixes this issue for me. Django 1.11.7, Python 3.6.3.

**Comment by Pankrat** [comment]
Finally got around trying to reproduce the `KeyError`. Unfortunately, I wasn't able to reproduce the error on a vanilla Django project (Django 1.11.8 or 2.0) on Python 3.5 or 3.6. The three constructor invocations look like multiple tracking layers have been injected into the Template class - even if the error wasn't raised I wonder if the tracking would return accurate results in this scenario. 

How do you run your app server when this error occurs? Are you using `runserver`? If yes, could you try reproducing the issue with [`--nothreading`](https://docs.djangoproject.com/en/2.0/ref/django-admin/#cmdoption-runserver-nothreading)?

@Schnouki Thanks for testing the fix. I'll include it soon. I'd still like to find a way to reproduce the issue if at all possible.

@karolyi I think this is a separate issue. @mrJean1 was already looking into that but it'll take a bit before this can be resolved. Feel free to open a new issue and attach as much information as possible for trying to reproduce this. Thanks!

**Comment by biswaz** [comment]
@Pankrat Could not reproduce with --no-threading
I found the issue  when using runserver and opening multiple instance pages of a model, from the admin panel rapidly. I didn't encounter the issue when doing it slowly, one by one.

Reproducable with these requirements: https://github.com/IEEEKeralaSection/rescuekerala/blob/master/requirements.txt
https://github.com/IEEEKeralaSection/rescuekerala/blob/master/requirements_debug.txt
