### ISSUE TITLE
Cannot import process due to empty line in /proc/self/status

### ISSUE THREAD

**Issue by dnlsng** [pympler/pympler#67]
Trying to import process is failing after updating the kernel on Ubuntu 16.04

```
$ python3 -c 'from pympler import process'                                                 
Traceback (most recent call last):                                                                                                          
  File "<string>", line 1, in <module>                                                                                                      
  File "/usr/local/lib/python3.5/dist-packages/pympler/process.py", line 192, in <module>                                                   
    if _ProcessMemoryInfoProc().update():  # pragma: no branch                                                                              
  File "/usr/local/lib/python3.5/dist-packages/pympler/process.py", line 63, in __init__                                                    
    self.available = self.update()                                                                                                          
  File "/usr/local/lib/python3.5/dist-packages/pympler/process.py", line 147, in update                                                     
    key, value = entry.split(':', 1)                                                                                                        
ValueError: not enough values to unpack (expected 2, got 1)
```
```
$ uname -a
Linux prdonkey002 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
There is now an empty line in the output of `/proc/self/status`. Should empty lines should be ignored?
```
$ cat /proc/self/status
Name:   cat
State:  R (running)
Tgid:   7428
Ngid:   0
Pid:    7428
PPid:   4375
TracerPid:      0
Uid:    10037   10037   10037   10037
Gid:    10037   10037   10037   10037
FDSize: 256
Groups: 10008 10015 10037 20004 35012 35017
NStgid: 7428
NSpid:  7428
NSpgid: 7428
NSsid:  4375
VmPeak:   123504 kB
VmSize:   123504 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:       720 kB
VmRSS:       720 kB
VmData:      320 kB
VmStk:       132 kB
VmExe:        48 kB
VmLib:      1944 kB
VmPTE:        44 kB
VmPMD:        12 kB
VmSwap:        0 kB
HugetlbPages:          0 kB
Threads:        1
SigQ:   0/1030577
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000000000
SigCgt: 0000000000000000
CapInh: 0000000000000000
CapPrm: 0000000000000000
CapEff: 0000000000000000
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
Seccomp:        0

Speculation_Store_Bypass:       vulnerable
Cpus_allowed:   ffff
Cpus_allowed_list:      0-15
Mems_allowed:   00000000,00000003
Mems_allowed_list:      0-1
voluntary_ctxt_switches:        0
nonvoluntary_ctxt_switches:     1
```

**Comment by Pankrat** [comment]
Thanks for the report! This should be fixed now on master.
