### ISSUE TITLE
KeyError: "asizeof typedef (48, 0, None, None, True, 'static', <class 'range'>) bad: (<class 'range' def>, <class 'range'>) True builtins range"

### ISSUE THREAD

**Issue by laurentbetti** [pympler/pympler#76]
Django 1.11 / Django debug toolbar 1.10.1 / Pympler 0.6

I'm getting this error:
`KeyError: "asizeof typedef (48, 0, None, None, True, 'static', <class 'range'>) bad: (<class 'range' def>, <class 'range'>) True builtins range"`,

when launching runserver, after having configured debug_toolbar as follows :

    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        ...
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'pympler.panels.MemoryPanel'
    ]

Any idea how this can be solved?

**Comment by mrJean1** [comment]
Can you show the entire traceback?

**Comment by laurentbetti** [comment]
Of course, here it is:
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f53f501d400>
Traceback (most recent call last):
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/debug_toolbar/apps.py", line 20, in check_middleware
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/debug_toolbar/middleware.py", line 18, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/debug_toolbar/toolbar.py", line 136, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/debug_toolbar/toolbar.py", line 129, in get_urls
    for panel_class in cls.get_panel_classes():
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/debug_toolbar/toolbar.py", line 112, in get_panel_classes
    for panel_path in dt_settings.get_panels()
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/debug_toolbar/toolbar.py", line 112, in <listcomp>
    for panel_path in dt_settings.get_panels()
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/laurent/.pyenv/versions/3.6.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/pympler/panels.py", line 25, in <module>
    from pympler.classtracker import ClassTracker
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/pympler/classtracker.py", line 17, in <module>
    from pympler.classtracker_stats import ConsoleStats
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/pympler/classtracker_stats.py", line 11, in <module>
    from pympler.asizeof import Asized
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/pympler/asizeof.py", line 1522, in <module>
    _typedef_both(xrange)
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/pympler/asizeof.py", line 1302, in _typedef_both
    v.save(t, base=base, heap=heap)
  File "/home/laurent/.pyenv/versions/my_app/lib/python3.6/site-packages/pympler/asizeof.py", line 1246, in save
    raise KeyError('asizeof typedef %r bad: %s' % (self, s))
KeyError: "asizeof typedef (48, 0, None, None, True, 'static', <class 'range'>) bad: (<class 'range' def>, <class 'range'>) True builtins range"

**Comment by mrJean1** [comment]
Great!  I’m unable to investigate, test and post a fix until next week.  The problem is `xrange` in Python 3.6.  In the mean time, one way to avoid the exception would be to change line 1523 of `asizeof.py` from

`except NameError:`

to

`except (KeyError, NameError):`

**Comment by mrJean1** [comment]
Just submitted `asizeof.py` 18.09.24 to fix the `KeyError`.  The error was thrown if `xrange` is set to `range` in Python 3+.  This `asizeof.py` also contains the fixes for 2 previous issues, #74 and #72.

**Comment by crystalneth** [comment]
Actually, now getting KeyError in a different location:

`/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in asized(*objs, **opts)
   2450     _asizer.reset(**opts)
   2451     if objs:
-> 2452         t = _asizer.asized(*objs)
   2453         _asizer.print_stats(objs, opts=opts, sized=t)  # show opts as _kwdstr
   2454         _asizer._clear()

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in asized(self, *objs, **opts)
   2014         if opts:
   2015             self.set(**opts)
-> 2016         _, t = self._sizes(objs, Asized)
   2017         if len(t) == 1:
   2018             t = t[0]

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizes(self, objs, sized)
   1988                 self._seen[i] += 1
   1989             else:
-> 1990                 s[i] = self._sizer(o, 0, sized)
   1991             t.append(s[i])
   1992         if sized:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1959                                     t.name = o.name
   1960                                 else:
-> 1961                                     t = z(o, d, sized)
   1962                                     t.name = self._nameof(o)
   1963                                 rs.append(t)

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1965                         else:  # just size and accumulate
   1966                             for o in r(obj, False):
-> 1967                                 s += z(o, d, None)
   1968                         # recursion depth reached
   1969                         if self._depth < d:

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _sizer(self, obj, deep, sized)
   1964                                 s += t.size
   1965                         else:  # just size and accumulate
-> 1966                             for o in r(obj, False):
   1967                                 s += z(o, d, None)
   1968                         # recursion depth reached

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _dict_refs(obj, named)
    706                 yield _NamedRef('[V] ' + s + ': ' + _repr(v), v)
    707         else:
--> 708             for k, v in _items(obj):
    709                 yield k
    710                 yield v

/usr/local/lib/python3.7/site-packages/pympler/asizeof.py in _items(obj)
    296     '''Return iter-/generator, preferably.
    297     '''
--> 298     return getattr(obj, 'iteritems', obj.items)()
    299 
    300 

/usr/local/lib/python3.7/site-packages/backtrader/utils/autodict.py in __getattr__(self, key)
    102             raise AttributeError
    103 
--> 104         return self[key]
    105 
    106     def __setattr__(self, key, value):

/usr/local/lib/python3.7/site-packages/backtrader/utils/autodict.py in __missing__(self, key)
     92     def __missing__(self, key):
     93         if self._closed:
---> 94             raise KeyError
     95 
     96         # value = self[key] = type(self)()

KeyError: 

`
