### ISSUE TITLE
ModuleNotFoundError: No module named "pympler" #91

### ISSUE THREAD

**Issue by sabuhish** [pympler/pympler#94]
I am getting this error in Python 3.6.7 as well , activated virtualenv still does not work.  

from pympler import summary, muppy
import psutil
import resource
import os
import sys

def memory_usage_psutil():
    # return the memory usage in MB
    process = psutil.Process(os.getpid())
    mem = process.get_memory_info()[0] / float(2 ** 20)
    return mem

def memory_usage_resource():
    rusage_denom = 1024.
    if sys.platform == 'darwin':
        # ... it seems that in OSX the output is different units ...
        rusage_denom = rusage_denom * rusage_denom
    mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / rusage_denom
    return mem

$ python3 people.py 
Traceback (most recent call last):
  File "people.py", line 1, in <module>
    import mem_profile
  File "/home/user/Documents/corey_python/code_snippets/Generators/mem_profile.py", line 1, in <module>
    from pympler import summary, muppy
ModuleNotFoundError: No module named 'pympler'

**Comment by mikhachev** [comment]
I've just solved this problem in PyCharm. File-Settings-Project-Project Interperter 
+ in the right (install) - find pympler in the left -install package

**Comment by shubhamk-mindtickle** [comment]
Try installing pympler with pip3. Something like 
pip3 install Pympler
